---
trigger:
  tags:
    include:
    - '*'
    
pool:
  vmImage: "ubuntu-latest"

variables:
  containerregistry: "ContainerRegistryElvia"
  imagetag: prod
  name: sesam-dummy-microservice
  namespace: sesam-extensions

resources:
  repositories:
    - repository: templates
      type: github
      name: 3lvia/core-azure-devops-templates
      endpoint: 3lvia

stages:
  - stage: Build
    jobs:
      - template: build.yaml@templates
        parameters:
          dockerfile: Dockerfile
